# Generated by Django 5.2.14 on 2026-05-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
    ]
