# Generated by Django 5.2.14 on 2026-06-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20260523_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='key',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='slide_type',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterModelTable(
            name='sliderimage',
            table='ecommerce_slider',
        ),
    ]
